import json
from pathlib import Path

import pytest

from agento_brain import rules

GOLDEN = json.loads((Path(__file__).parent / "golden_rules.json").read_text())

# Hand-picked expectations straight from plugin/core/task.spec.ts examples (tier at v1 granularity).
SPEC_EXPECTED = {
    "поправь опечатку в README": "sonnet",
    "fix the typo in CONTRIBUTING.md": "sonnet",
    "add a log line when the worker starts": "sonnet",
    "спроектируй архитектуру очереди задач с ретраями": "opus",
    "нужно мигрировать базу с MySQL на Postgres без простоя": "opus",
    "design a distributed rate limiter on top of Redis": "opus",
    "there is a deadlock between the scheduler and the worker pool, find it": "opus",
    "давай обсудим, как лучше организовать кэширование ответов": "opus",
    "отрефактори модуль авторизации целиком, он стал неподдерживаемым": "opus",
    "почему падает тест auth.spec, разберись": "sonnet",
    "implement a /health endpoint that returns the git sha": "sonnet",
    "refactor the billing module so invoices and payments are separate": "opus",
}


def test_golden_is_big_enough():
    assert len([g for g in GOLDEN if g["source"] == "spec-example"]) >= 50


@pytest.mark.parametrize("prompt,tier", SPEC_EXPECTED.items())
def test_spec_examples(prompt, tier):
    f = rules.extract_features(prompt, is_session_start=True)
    assert rules.classify_rules(f).tier == tier


@pytest.mark.parametrize("g", GOLDEN, ids=lambda g: g["prompt"][:40].replace("\n", " "))
def test_parity_with_typescript(g):
    """Exact parity with the real TS implementation (golden generated by running task.ts under node)."""
    f = rules.extract_features(g["prompt"], context_tokens=0, is_session_start=True)
    tf = g["features"]
    assert (f.heavy, f.light, f.plan) == (tf["keywords"]["heavy"], tf["keywords"]["light"], tf["keywords"]["plan"])
    assert f.prompt_chars == tf["promptChars"]
    assert f.prompt_lang == tf["promptLang"]
    assert f.has_code_block == tf["hasCodeBlock"]
    assert f.mentions_files == tf["mentionsFiles"]
    v = rules.classify_rules(f)
    tv = g["verdict"]
    assert (v.tier, v.effort, v.confidence, v.reasons) == (tv["tier"], tv["effort"], tv["confidence"], tv["reasons"])


def test_rules_never_answer_haiku():
    assert all(g["verdict"]["tier"] != "haiku" for g in GOLDEN)
